version: "3"

services:
  # postgresql:
  #   image: cr-preview.pentium.network/pncdn/postgres:13.2-alpine
  #   restart: always
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     PGDATA: ${POSTGRES_PGDATA}
  #   ports:
  #     - "${POSTGRES_PORT_HOST}:${POSTGRES_PORT}"
  #   volumes:
  #     - "${POSTGRES_ENTRYPOINT_INITDB_D_HOST}:${POSTGRES_ENTRYPOINT_INITDB_D}"
  #     - "${POSTGRES_PGDATA_HOST}:${POSTGRES_PGDATA}"
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
  #     interval: 10s
  #     timeout: 10s
  #     retries: 10
  #     start_period: 30s

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.25-management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - "./data/mq:/var/lib/rabbitmq"
    # healthcheck:
    #   test: rabbitmq-diagnostics -q ping
    #   interval: 30s
    #   timeout: 30s
    #   retries: 3
    ports:
        - 5672:5672
        - 15672:15672
