name: Pack and Release

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      # - 'v[12].[0-9]+.[0-9]+'
      - '*'

jobs:
  check:
    uses: ./.github/workflows/lint_and_test.yml

  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Golang
      uses: magnetikonline/action-golang-cache@v3
      with:
        go-version-file: go.mod

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v3
      with:
        distribution: goreleaser
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
